health-check/spring-boot/spring-boot-health-check-booster.yaml, rest-http-secured/spring-boot/spring-boot-rest-http-secured-booster.yaml
Removing these boosters from the catalog until they're completed (or at least more close to completion).
=> [SB-49] Remove Health Check and Secured Spring Boot boosters

configmap/vert.x/vertx-configmap-booster.yaml, crud/vert.x/vertx-crud-booster.yaml, rest-http/vert.x/vertx-http-booster.yaml
@gastaldi @ALRubinger I let you merge when you are ready.
=> use vert.x booster v1

metadata.json
This is part of https://github.com/openshiftio/launchpad-addon/issues/31
=> Introduce metadata.json 

circuit-breaker/spring-boot/spring-boot-circuit-breaker-booster.yaml, metadata.json
- Add Circuit Breaker booster to the metadata
- Create folder containing Spring Boot runtime
- Tested the zip file generated by the launcher
=> Add Circuit Breaker booster

metadata.json, rest-http/nodejs/nodejs-rest-http-booster.yaml
This PR adds a REST Level 0 booster for node.js.
This PR will be connected to other PRs in various repos, so this isn't to be merged yet.
Just getting the ball rolling with Node.js Integration
=> [WIP] - Addition of node.js rest booster

metadata.json, rest-http/nodejs/nodejs-rest-http-booster.yaml
=> add v1.0.0 nodejs rest http booster

health-check/nodejs/nodejs-health-check-booster.yaml
Adding the nodejs health check booster.  Will also add to the next/oso free branch if this makes it in.
A PR for the docs is here https://github.com/openshiftio/appdev-documentation/pull/453
=> add nodejs health check booster

health-check/nodejs/nodejs-health-check-booster.yaml
adding in the nodejs health check booster for release
=> add nodejs health check booster v1.0.0

crud/nodejs/nodejs-crud-booster.yaml
Adding the Nodejs CRUD Booster
=> feat: adding the nodejs crud booster

crud/nodejs/nodejs-crud-booster.yaml
Looks like we are ready for this to be released to the public, yikes :)
=> Add node.js CRUD booster for next release

circuit-breaker/nodejs/nodejs-circuit-breaker-booster.yaml
This adds the circuit breaker booster for the Node.js runtime.
=> feat: add NodeJS circuit breaker booster

circuit-breaker/nodejs/nodejs-circuit-breaker-booster.yaml
=> update nodejs circuit breaker booster to v0.2.1

crud/nodejs/nodejs-crud-booster.yaml, health-check/nodejs/nodejs-health-check-booster.yaml, rest-http/nodejs/nodejs-rest-http-booster.yaml
Updates the REST Level 0, Health Check and CRUD node boosters
=> update node boosters to support s2i

configmap/nodejs/nodejs-configmap-booster.yaml
this adds the nodejs configmap booster
=> feat: add configmap booster for nodejs

circuit-breaker/spring-boot/community/spring-boot-circuit-breaker-community.yaml, circuit-breaker/spring-boot/redhat/spring-boot-circuit-breaker-redhat.yaml, configmap/spring-boot/community/spring-boot-configmap-community.yaml, configmap/spring-boot/redhat/spring-boot-configmap-redhat.yaml, crud/spring-boot/community/spring-boot-rest-http-crud-community.yaml, crud/spring-boot/redhat/spring-boot-rest-http-crud-redhat.yaml, health-check/spring-boot/community/spring-boot-health-check-community.yaml, health-check/spring-boot/redhat/spring-boot-health-check-redhat.yaml, rest-http-secured/spring-boot/redhat/spring-boot-http-secured-redhat.yaml, rest-http/spring-boot/community/spring-boot-rest-http-community.yaml, rest-http/spring-boot/redhat/spring-boot-rest-http-redhat.yaml
Remove redhat version for HTTP secured since we haven't published it.
=> Update Spring Boot boosters. 

configmap/nodejs/nodejs-configmap-booster.yaml, health-check/nodejs/nodejs-health-check-booster.yaml, rest-http/nodejs/nodejs-rest-http-booster.yaml
also adds the configmap booster for nodejs
=> update: update nodejs boosters to fix nsp security issues

circuit-breaker/nodejs/nodejs-circuit-breaker-booster.yaml, configmap/nodejs/nodejs-configmap-booster.yaml, crud/nodejs/nodejs-crud-booster.yaml, health-check/nodejs/nodejs-health-check-booster.yaml, rest-http/nodejs/nodejs-rest-http-booster.yaml
related to this issue bucharest-gold/nodejs-rest-http-crud#24
=> update: update application yaml for nodejs boosters

rest-http-secured/nodejs-rest-http-secured-booster.yaml
docs aren't yet added,  but i know there is some changes happening there.
but i just wanted to get this in here
=> update: add nodejs rest secured booster

circuit-breaker/vert.x/community/vertx-circuit-breaker-community-booster.yaml, circuit-breaker/vert.x/redhat/vertx-circuit-breaker-redhat-booster.yaml, configmap/vert.x/community/vertx-configmap-community-booster.yaml, configmap/vert.x/redhat/vertx-configmap-redhat-booster.yaml, crud/vert.x/community/vertx-crud-community-booster.yaml, crud/vert.x/redhat/vertx-crud-redhat-booster.yaml, health-check/vert.x/community/vertx-health-check-community-booster.yaml, health-check/vert.x/redhat/vertx-health-check-redhat-booster.yaml, rest-http/vert.x/community/vertx-http-community-booster.yaml, rest-http/vert.x/redhat/vertx-http-redhat-booster.yaml
=> update vert.x boosters

rest-http-secured/nodejs/nodejs-rest-http-secured-booster.yaml
adds the nodejs secure http booster
=> add secured nodejs booster - next branch

README.md
This is to address feedback we had from the runtime teams: it wasn't
always clear which branch should be updated and when.
=> clarify branching and tagging strategy

circuit-breaker/wildfly-swarm/redhat/wildfly-swarm-circuit-breaker-redhat.yaml, configmap/wildfly-swarm/redhat/wildfly-swarm-configmap-redhat.yaml, crud/wildfly-swarm/redhat/wildfly-swarm-rest-http-crud-redhat.yaml, health-check/wildfly-swarm/redhat/wildfly-swarm-health-check-redhat.yaml, rest-http-secured/wildfly-swarm/redhat/wildfly-swarm-rest-http-secured-redhat.yaml, rest-http/wildfly-swarm/redhat/wildfly-swarm-rest-http-redhat.yaml
Align the master branch with new repo locations
=> Use separate repos for swarm prod boosters (master)

circuit-breaker/nodejs/nodejs-circuit-breaker-booster.yaml, configmap/nodejs/nodejs-configmap-booster.yaml, crud/nodejs/nodejs-crud-booster.yaml, health-check/nodejs/nodejs-health-check-booster.yaml, rest-http/nodejs/nodejs-rest-http-booster.yaml
@gastaldi for that issue https://github.com/fabric8-launcher/launcher-planning/issues/90
=> update: nodejs boosters now using the incremental flag

circuit-breaker/nodejs/booster.yaml, configmap/nodejs/booster.yaml, crud/nodejs/booster.yaml, health-check/nodejs/booster.yaml, rest-http/nodejs/booster.yaml
The versions for both staging and production should be the same
=> Node js version updates

circuit-breaker/nodejs/booster.yaml
This fixes issues with route creation by nodeshift.
See: https://github.com/bucharest-gold/nodeshift/issues/184
=> Bump node circuit breaker to v1.0.0

configmap/nodejs/booster.yaml, crud/nodejs/booster.yaml, health-check/nodejs/booster.yaml, rest-http-secured/nodejs/booster.yaml, rest-http/nodejs/booster.yaml
This fixes issues with route creation by nodeshift.
see https://github.com/bucharest-gold/nodeshift/issues/184
=> update nodejs boosters.

vert.x/community/circuit-breaker/booster.yaml, vert.x/community/configmap/booster.yaml, vert.x/community/crud/booster.yaml, vert.x/community/health-check/booster.yaml, vert.x/community/rest-http-secured/booster.yaml, vert.x/community/rest-http/booster.yaml, vert.x/redhat/circuit-breaker/booster.yaml, vert.x/redhat/configmap/booster.yaml, vert.x/redhat/crud/booster.yaml, vert.x/redhat/health-check/booster.yaml, vert.x/redhat/rest-http/booster.yaml
These boosters use the booster-parent v20.
=> Update booster version

vert.x/community/rest-http/booster.yaml
This version should fix the pipeline issue, the broken yaml and so on.... hopefully.
=> update http booster version

spring-boot/1.5.10-community/health-check/booster.yaml, spring-boot/1.5.10-community/rest-http/booster.yaml, vert.x/community/health-check/booster.yaml, vert.x/community/rest-http/booster.yaml, wildfly-swarm/community/health-check/booster.yaml, wildfly-swarm/community/rest-http/booster.yaml
supress the community runtime versions in the osio so that only rhoar version is used
=> supress the community runtime versions in the osio

nodejs/community/cache/booster.yaml, nodejs/community/circuit-breaker/booster.yaml, nodejs/community/configmap/booster.yaml, nodejs/community/crud/booster.yaml, nodejs/community/health-check/booster.yaml, nodejs/community/rest-http-secured/booster.yaml, nodejs/community/rest-http/booster.yaml, nodejs/redhat/cache/booster.yaml, nodejs/redhat/circuit-breaker/booster.yaml, nodejs/redhat/configmap/booster.yaml, nodejs/redhat/crud/booster.yaml, nodejs/redhat/health-check/booster.yaml, nodejs/redhat/rest-http-secured/booster.yaml, nodejs/redhat/rest-http/booster.yaml
The first commit is adding in the node.js cache booster,  sort of needs to wait on #190 since i've only added the node.js folder structure and didn't update the metadata.yaml
The second commit is for updating all the current node.js boosters to the latest tagged versions
=> Nodejs cache mission and other booster updates

metadata.yaml
Updating the catalog is quite error-prone…
=> Forgot to update the prod version in metadata… :(

metadata.yaml, spring-boot/current-community/cache/booster.yaml, spring-boot/current-community/circuit-breaker/booster.yaml, spring-boot/current-community/configmap/booster.yaml, spring-boot/current-community/health-check/booster.yaml, spring-boot/current-community/istio-circuit-breaker/booster.yaml, spring-boot/current-community/istio-distributed-tracing/booster.yaml, spring-boot/current-community/istio-routing/booster.yaml, spring-boot/current-community/istio-security/booster.yaml, spring-boot/current-community/rest-http-secured/booster.yaml, spring-boot/current-community/rest-http/booster.yaml, spring-boot/current-osio/configmap/booster.yaml, spring-boot/current-redhat/circuit-breaker/booster.yaml, spring-boot/current-redhat/configmap/booster.yaml, spring-boot/current-redhat/health-check/booster.yaml, spring-boot/current-redhat/rest-http-secured/booster.yaml, spring-boot/current-redhat/rest-http/booster.yaml
Also unifies wording across Spring Boot boosters.
=> Add Istio booster implementation

metadata.yaml, spring-boot/current-osio/configmap/booster.yaml
@animuk could you verify that this fixes the Spring Boot ConfigMap issue?
=> Update SB OSIO ConfigMap booster data

metadata.yaml
=> chore(docs): improved mission descriptions

metadata.yaml, nodejs/v10-redhat/cache/booster.yaml, nodejs/v10-redhat/circuit-breaker/booster.yaml, nodejs/v10-redhat/configmap/booster.yaml, nodejs/v10-redhat/crud/booster.yaml, nodejs/v10-redhat/health-check/booster.yaml, nodejs/v10-redhat/rest-http-secured/booster.yaml, nodejs/v10-redhat/rest-http/booster.yaml
This adds node 10 for the "RHOAR" production boosters.
I'm keeping this separate since this might need some more release notes and such before it is merged
=> Add node 10 for RHOAR boosters

README.md, spring-boot/current-community/health-check/booster.yaml, spring-boot/current-community/rest-http/booster.yaml, spring-boot/current-redhat/health-check/booster.yaml, spring-boot/current-redhat/rest-http/booster.yaml, vert.x/community/health-check/booster.yaml, vert.x/community/rest-http/booster.yaml, wildfly-swarm/community/health-check/booster.yaml, wildfly-swarm/community/rest-http/booster.yaml
This flag is no longer used in OSIO
=> Remove worksWithLegacyOsio: true flag

metadata.yaml, spring-boot/current-community/cache/booster.yaml, spring-boot/current-community/circuit-breaker/booster.yaml, spring-boot/current-community/configmap/booster.yaml, spring-boot/current-community/crud/booster.yaml, spring-boot/current-community/health-check/booster.yaml, spring-boot/current-community/istio-circuit-breaker/booster.yaml, spring-boot/current-community/istio-distributed-tracing/booster.yaml, spring-boot/current-community/istio-routing/booster.yaml, spring-boot/current-community/istio-security/booster.yaml, spring-boot/current-community/rest-http-secured/booster.yaml, spring-boot/current-community/rest-http/booster.yaml, spring-boot/current-redhat/cache/booster.yaml, spring-boot/current-redhat/circuit-breaker/booster.yaml, spring-boot/current-redhat/configmap/booster.yaml, spring-boot/current-redhat/crud/booster.yaml, spring-boot/current-redhat/health-check/booster.yaml, spring-boot/current-redhat/rest-http-secured/booster.yaml, spring-boot/current-redhat/rest-http/booster.yaml
Do not merge. Pending for the productised artefacts.
=> Update Spring Boot to 1.5.13.RELEASE

nodejs/v10-community/istio-circuit-breaker/booster.yaml, nodejs/v10-community/istio-distributed-tracing/booster.yaml, nodejs/v8-community/istio-circuit-breaker/booster.yaml, nodejs/v8-community/istio-distributed-tracing/booster.yaml
This adds the Istio tracing booster for node.js
also updates the Istio CB booster with some small updates
=> Nodejs istio tracing and updates

vert.x/community/cache/booster.yaml, vert.x/community/circuit-breaker/booster.yaml, vert.x/community/configmap/booster.yaml, vert.x/community/crud/booster.yaml, vert.x/community/health-check/booster.yaml, vert.x/community/rest-http-secured/booster.yaml, vert.x/community/rest-http/booster.yaml, vert.x/redhat/cache/booster.yaml, vert.x/redhat/circuit-breaker/booster.yaml, vert.x/redhat/configmap/booster.yaml, vert.x/redhat/crud/booster.yaml, vert.x/redhat/health-check/booster.yaml, vert.x/redhat/rest-http-secured/booster.yaml, vert.x/redhat/rest-http/booster.yaml
This update includes the template fix due to a bug (behavior change) introduced by the latest FMP version.
=> Update Vert.x booster versions

.github/CODEOWNERS, metadata.yaml, thorntail/community/common.yaml, thorntail/community/istio-circuit-breaker/booster.yaml, thorntail/community/istio-distributed-tracing/booster.yaml, thorntail/community/istio-routing/booster.yaml, thorntail/community/istio-security/booster.yaml
Also update Istio Boosters to latest tag
=> Add Thorntail project metadata and move Istio Boosters under Thorntail

vert.x/community/istio-circuit-breaker/booster.yaml, vert.x/community/istio-distributed-tracing/booster.yaml, vert.x/community/istio-routing/booster.yaml, vert.x/community/istio-security/booster.yaml
Add the 4 boosters using Istio for Eclipse Vert.x
=> Register Vert.x boosters using Istio

metadata.yaml, nodejs/v10-community/messaging/booster.yaml, nodejs/v10-redhat/messaging/booster.yaml, nodejs/v8-community/messaging/booster.yaml, nodejs/v8-redhat/messaging/booster.yaml
This adds the Messaging Info to the metadata and also adds the Node.js version of the booster
=> AMQP Booster

thorntail/community/cache/booster.yaml, wildfly-swarm/redhat/cache/booster.yaml, wildfly-swarm/redhat/circuit-breaker/booster.yaml
Community
cache: https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-cache/releases/tag/3
Product:
cache: https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-cache-redhat/releases/tag/7.1.0-redhat-2
circuit breaker: https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-circuit-breaker-redhat/releases/tag/7.1.0-redhat-2
=> THORN-2130: Thorntail updates for train E

metadata.yaml
=> add a missing 0 in the productized Vert.x version

metadata.yaml
Needed for https://github.com/fabric8-launcher/launcher-planning/issues/181
=> chore: remove Spring Boot icon

thorntail/community/rest-http/booster.yaml
https://github.com/openshiftio/openshift.io/issues/4547
=> diable booster on osio due to OOM

thorntail/community/health-check/booster.yaml
as per https://github.com/openshiftio/openshift.io/issues/4547
=> Disabled failing booster in osio

nodejs/v10-community/health-check/booster.yaml, nodejs/v10-community/rest-http/booster.yaml
Reverts fabric8-launcher/launcher-booster-catalog#305
=> Revert "enabling community nodejs v10 healthcheck and http"

fuse/community/circuit-breaker/booster.yaml, fuse/community/configmap/booster.yaml, fuse/community/health-check/booster.yaml, fuse/community/istio-distributed-tracing/booster.yaml, fuse/community/rest-http/booster.yaml, fuse/redhat/circuit-breaker/booster.yaml, fuse/redhat/configmap/booster.yaml, fuse/redhat/health-check/booster.yaml, fuse/redhat/istio-distributed-tracing/booster.yaml, fuse/redhat/rest-http/booster.yaml
it includes notably the fix to have them compatible with odo
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> Use latest tag of Fuse boosters

catalog.json, metadata.json
Manual update of boosters catalgue
=> chore: update Spring Boot to 2.1.12

catalog.json
I had to release Thorntail 2.7.3 examples again to fix a bug
in S2I flow testing.
=> Thorntail 2.7.3, part 2
