configmap/vert.x/vertx-configmap-booster.yaml
crud/vert.x/vertx-crud-booster.yaml

Update vert.x booster version

---

circuit-breaker/nodejs/nodejs-circuit-breaker-booster.yaml

This adds a tagged version of the NodeJS circuit breaker booster to the catalog.

feat: add v0.2.0 nodejs circuit breaker booster

---

configmap/wildfly-swarm/redhat/wildfly-swarm-configmap-redhat.yaml

The configmap is created during s2i setup

Fix OBST-384 for Swarm 

---

circuit-breaker/nodejs/nodejs-circuit-breaker-booster.yaml
configmap/nodejs/nodejs-configmap-booster.yaml
crud/nodejs/nodejs-crud-booster.yaml
health-check/nodejs/nodejs-health-check-booster.yaml
rest-http/nodejs/nodejs-rest-http-booster.yaml

There were some security issues that came up during npm installs,  so this updates the boosters to patch versions of those dependecies

update: update nodejs boosters to fix nsp security issues

---

circuit-breaker/vert.x/community/vertx-circuit-breaker-community-booster.yaml
circuit-breaker/vert.x/redhat/vertx-circuit-breaker-redhat-booster.yaml
configmap/vert.x/community/vertx-configmap-community-booster.yaml
configmap/vert.x/redhat/vertx-configmap-redhat-booster.yaml
crud/vert.x/community/vertx-crud-community-booster.yaml
crud/vert.x/redhat/vertx-crud-redhat-booster.yaml
health-check/vert.x/community/vertx-health-check-community-booster.yaml
health-check/vert.x/redhat/vertx-health-check-redhat-booster.yaml
rest-http-secured/vert.x/community/vertx-sso-community-booster.yaml
rest-http-secured/vert.x/redhat/vertx-sso-redhat-booster.yaml
rest-http/vert.x/community/vertx-http-community-booster.yaml
rest-http/vert.x/redhat/vertx-http-redhat-booster.yaml

Use CR1 bits - do not merge before CR1 artifacts are made available in a Maven repository.

Update vert.x booster versions.

---

circuit-breaker/spring-boot/1.5.10-community/booster.yaml
circuit-breaker/spring-boot/1.5.8-community/booster.yaml
circuit-breaker/spring-boot/1.5.8-redhat/booster.yaml
circuit-breaker/spring-boot/common.yaml
configmap/spring-boot/1.5.10-community/booster.yaml
configmap/spring-boot/1.5.8-community/booster.yaml
configmap/spring-boot/1.5.8-redhat/booster.yaml
configmap/spring-boot/common.yaml
crud/spring-boot/1.5.10-community/booster.yaml
crud/spring-boot/1.5.8-community/booster.yaml
crud/spring-boot/1.5.8-redhat/booster.yaml
crud/spring-boot/common.yaml
health-check/spring-boot/1.5.10-community/booster.yaml
health-check/spring-boot/1.5.8-community/booster.yaml
health-check/spring-boot/1.5.8-redhat/booster.yaml
health-check/spring-boot/common.yaml
rest-http-secured/spring-boot/1.5.10-community/booster.yaml
rest-http-secured/spring-boot/1.5.8-community/booster.yaml
rest-http-secured/spring-boot/1.5.8-redhat/booster.yaml
rest-http-secured/spring-boot/common.yaml
rest-http/spring-boot/1.5.10-community/booster.yaml
rest-http/spring-boot/1.5.8-community/booster.yaml
rest-http/spring-boot/1.5.8-redhat/booster.yaml
rest-http/spring-boot/common.yaml

- New runtime version is named 1.5.10-community
- Renamed previous runtimes:
+ community -> 1.5.8-community
+ redhat -> 1.5.8-redhat
- Moved source.git.url definition for all boosters to common.yaml.

SB-469: Add 1.5.10 runtime version and associated boosters.

---

vert.x/community/rest-http/booster.yaml

After having fixed the hardcoded FMP version

Update the Vert.x HTTP booster version

---

vert.x/community/circuit-breaker/booster.yaml
vert.x/community/configmap/booster.yaml
vert.x/community/crud/booster.yaml
vert.x/community/health-check/booster.yaml
vert.x/community/rest-http/booster.yaml
vert.x/redhat/circuit-breaker/booster.yaml
vert.x/redhat/configmap/booster.yaml
vert.x/redhat/crud/booster.yaml
vert.x/redhat/health-check/booster.yaml
vert.x/redhat/rest-http-secured/booster.yaml
vert.x/redhat/rest-http/booster.yaml

This update should fix the `image:' '` issue from the FMP (https://github.com/fabric8io/fabric8-maven-plugin/issues/1237). The `application.yaml` are now generated without the `fabric8.openshift.trimImageInContainerSpec` option.
This update also declare the Redhat SSO booster using redhat bits.
Finally, the boosters have been their licenses file (licenses.xml, licenses.html) updated.

Update Vert.x booster versions

---

spring-boot/current-osio/configmap/booster.yaml
wildfly-swarm/redhat/configmap/booster.yaml
wildfly-swarm/redhat/health-check/booster.yaml

Build for springboot-configmap, wildfly-swarm-configmap and wildfly-swarm-health-check boosters are failing so disabling that.
Logs:
Springboot-configmap: https://github.com/openshiftio/openshift.io/issues//3131
Wildfly-Swarm-configmap: https://github.com/openshiftio/openshift.io/issues//3134
Wildfly-Swarm-health-check: https://github.com/openshiftio/openshift.io/issues//3124

Disable springboot-configmap, wildfly-swarm-configmap and wildfly-swarm-health-check booster

---

wildfly-swarm/redhat/rest-http/booster.yaml

wildflyswarm rest-http booster build is failing so disabling this.
Related Issue: https://github.com/openshiftio/openshift.io/issues/3430

Disabling wildfly-swarm rest-http booster

---

vert.x/redhat/configmap/booster.yaml

This PR updates the vert.x config map booster (-redhat) version to enable local development in Che.
It's related to:
* https://github.com/openshiftio-vertx-boosters/vertx-configmap-booster-redhat/issues/14
* https://github.com/openshiftio/openshift.io/issues/2988#issuecomment-386788483

update booster version to 14

---

spring-boot/current-redhat/health-check/booster.yaml
spring-boot/current-redhat/rest-http/booster.yaml

An empty metadata tag causes the following exception:
```
Caused by: java.lang.NullPointerException
  | at java.util.Collections$UnmodifiableMap.<init>(Collections.java:1446)
  | at java.util.Collections.unmodifiableMap(Collections.java:1433)
  | at io.fabric8.launcher.booster.catalog.Booster.getMetadata(Booster.java:260)
  | at io.fabric8.launcher.web.endpoints.BoosterCatalogEndpoint.lambda$getRuntimes$0(BoosterCatalogEndpoint.java:110)
  | at java.util.Optional.ifPresent(Optional.java:159)
  | at io.fabric8.launcher.web.endpoints.BoosterCatalogEndpoint.getRuntimes(BoosterCatalogEndpoint.java:108)
  | at io.fabric8.launcher.web.endpoints.BoosterCatalogEndpoint$Proxy$_$$_WeldSubclass.getRuntimes(Unknown Source)
  | at io.fabric8.launcher.web.endpoints.BoosterCatalogEndpoint$Proxy$_$$_WeldC …
```

fix(descriptor): remove empty metadata

---

fuse/2.21.0-community/health-check/booster.yaml
fuse/2.21.0-community/rest-http/booster.yaml
fuse/7.0.0-redhat/health-check/booster.yaml
fuse/7.0.0-redhat/rest-http/booster.yaml

Some booster.yaml files had extra invisible characters throwing off the parser

fix(fuse): fixed fuse boosters

---

metadata.yaml
vert.x/redhat/cache/booster.yaml
vert.x/redhat/circuit-breaker/booster.yaml
vert.x/redhat/configmap/booster.yaml
vert.x/redhat/crud/booster.yaml
vert.x/redhat/health-check/booster.yaml
vert.x/redhat/rest-http-secured/booster.yaml
vert.x/redhat/rest-http/booster.yaml

* Update the Vert.x version in the metadata.yaml
* Update the Vert.x booster versions
This commit only changes the boosters using productized modules.

Vert.x 3.5.1.redhat-004 updates

---

metadata.yaml
vert.x/community/cache/booster.yaml
vert.x/community/circuit-breaker/booster.yaml
vert.x/community/configmap/booster.yaml
vert.x/community/crud/booster.yaml
vert.x/community/health-check/booster.yaml
vert.x/community/rest-http-secured/booster.yaml
vert.x/community/rest-http/booster.yaml
vert.x/redhat/cache/booster.yaml
vert.x/redhat/circuit-breaker/booster.yaml
vert.x/redhat/configmap/booster.yaml
vert.x/redhat/crud/booster.yaml
vert.x/redhat/health-check/booster.yaml
vert.x/redhat/rest-http-secured/booster.yaml
vert.x/redhat/rest-http/booster.yaml

These new versions are using:
* Vert.x Red Hat: 3.5.1.redhat-004
* Vert.x Community: 3.5.2 (updated)
* FMP Version: 3.5.40 (updated)
* VMP Version: 1.0.15
* booster-parent version: 23 (updated)
This release is related to https://github.com/openshiftio/booster-parent/issues/29.
Community boosters have been updated to Vert.x 3.5.2.

Update Vert.x boosters - booster parent 23, Vert.x Community 3.5.2

---

nodejs/v10-community/istio-circuit-breaker/booster.yaml
nodejs/v10-community/istio-distributed-tracing/booster.yaml
nodejs/v10-community/istio-routing/booster.yaml
nodejs/v10-community/istio-security/booster.yaml
nodejs/v8-community/istio-circuit-breaker/booster.yaml
nodejs/v8-community/istio-distributed-tracing/booster.yaml
nodejs/v8-community/istio-routing/booster.yaml
nodejs/v8-community/istio-security/booster.yaml

These updated versions use Istio 0.8.0

chore: update node.js boosters

---

metadata.yaml
vert.x/community/cache/booster.yaml
vert.x/community/circuit-breaker/booster.yaml
vert.x/community/configmap/booster.yaml
vert.x/community/crud/booster.yaml
vert.x/community/health-check/booster.yaml
vert.x/community/istio-circuit-breaker/booster.yaml
vert.x/community/istio-distributed-tracing/booster.yaml
vert.x/community/istio-security/booster.yaml
vert.x/community/rest-http-secured/booster.yaml
vert.x/community/rest-http/booster.yaml
vert.x/redhat/cache/booster.yaml
vert.x/redhat/circuit-breaker/booster.yaml
vert.x/redhat/configmap/booster.yaml
vert.x/redhat/crud/booster.yaml
vert.x/redhat/health-check/booster.yaml
vert.x/redhat/rest-http-secured/booster.yaml
vert.x/redhat/rest-http/booster.yaml

Are updated in this PR:
* community booster to Vert.x 3.5.3
* boosters using productized version of the runtime 3.5.3-redhat-0001
* Vert.x Istio boosters  to Vert.x 3.5.3

Update Vert.x boosters

---

vert.x/community/cache/booster.yaml
vert.x/community/circuit-breaker/booster.yaml
vert.x/community/configmap/booster.yaml
vert.x/community/crud/booster.yaml
vert.x/community/health-check/booster.yaml
vert.x/community/rest-http-secured/booster.yaml
vert.x/community/rest-http/booster.yaml
vert.x/redhat/cache/booster.yaml
vert.x/redhat/circuit-breaker/booster.yaml
vert.x/redhat/configmap/booster.yaml
vert.x/redhat/crud/booster.yaml
vert.x/redhat/health-check/booster.yaml
vert.x/redhat/rest-http-secured/booster.yaml
vert.x/redhat/rest-http/booster.yaml

This PR updates the Vert.x booster versions and fix the broken template generation.
Now the templates are tested as part of our CI jobs, so we should not have such kind of issues anymore.... well, in theory.

Bump Vert.x booster versions

---

nodejs/v10-community/istio-circuit-breaker/booster.yaml
nodejs/v10-redhat/istio-circuit-breaker/booster.yaml
nodejs/v8-community/istio-circuit-breaker/booster.yaml
nodejs/v8-redhat/istio-circuit-breaker/booster.yaml

This update includes fixes for https://issues.jboss.org/browse/NODE-222

chore: update Node istio circuit breaker boosters to the latest.

---

nodejs/v10-community/configmap/booster.yaml
nodejs/v10-redhat/configmap/booster.yaml
nodejs/v8-community/configmap/booster.yaml
nodejs/v8-redhat/configmap/booster.yaml

These new versions use volume mounts to expose the config maps to the application.  Inline with how the other runtimes are doing it

chore: update nodejs config map versions

---

nodejs/v10-community/health-check/booster.yaml
nodejs/v10-community/rest-http/booster.yaml

This enables community nodejs health-check and http
When testing locally, i noticed that I was stuck on the dependency screen. The dependency screen states that i need to select a runtime and mission - even though I have already done so. If you skip the dependency screen and make it to the end of the process, you cannot complete the process. It says the process is incomplete. When selecting the "incomplete" button, I am guided back to the start of the process to select a runtime and mission. Upon trying again, when I reached the github part of the process I was unable to click the arrows to continue. The screenshot shows the redhat version instead of the community version, but both were tested and both resulted in the same problem.

enabling community nodejs v10 healthcheck and http

---

spring-boot/current-community/messaging/booster.yaml
spring-boot/current-redhat/messaging/booster.yaml

Is it ok that a dependent service template file is named [service.yaml](https://github.com/snowdrop/spring-boot-messaging-work-queue-booster/blob/1.5.17-4/service.yaml) rather than `service.amqp.yaml` or `service.cache.yaml` like in other boosters? I can rename it for the next release.

Add Spring Boot messaging booster

---

golang/redhat/crud/booster.yaml

Disabling CRUD golang booster due to known pipeline issues

disable crud booster

---

README.md

SHA1 hash is not supported for source/git/ref value.
Updating Readme based on the discussion here: https://github.com/fabric8-launcher/launcher-booster-catalog-service/issues/31#issuecomment-474813604
ping @gastaldi

Clarify information about source/git/ref in Readme

---

fuse/community/istio-distributed-tracing/booster.yaml
fuse/redhat720/istio-distributed-tracing/booster.yaml
fuse/redhat730/istio-distributed-tracing/booster.yaml
fuse/redhat731/istio-distributed-tracing/booster.yaml
metadata.yaml
nodejs/v10-community/istio-distributed-tracing/booster.yaml
nodejs/v10-redhat/istio-distributed-tracing/booster.yaml
nodejs/v12-community/istio-distributed-tracing/booster.yaml
nodejs/v8-community/istio-distributed-tracing/booster.yaml
nodejs/v8-redhat/istio-distributed-tracing/booster.yaml
spring-boot/current-community/istio-distributed-tracing/booster.yaml
spring-boot/current-redhat/istio-distributed-tracing/booster.yaml
spring-boot/previous-community/istio-distributed-tracing/booster.yaml
spring-boot/previous-redhat/istio-distributed-tracing/booster.yaml
thorntail/community/istio-distributed-tracing/booster.yaml
thorntail/redhat/istio-distributed-tracing/booster.yaml
vert.x/community/istio-distributed-tracing/booster.yaml

ISTIO - Distributed tracing was removed in the previous commit. This one puts it back

chore: put ISTIO - Distributed Tracing back
